### ISSUE TITLE
workgroup org improvements suggestion  

### ISSUE THREAD

**Issue by gregory1g** [camaraproject/RegionDeviceCount#19]
Based on experience working in other workgroups I would suggest the following adjustments:
1) avoid short notice meeting reschedule (example: meeting on 24.05 was rescheduled  just one day upfront)
2) be strict on time timebox  - people may have other meetings directly after the workgroup meeting
3) avoid fast buddy code review and given people some time to review the change (example: pull request #18 was created, approved and merged in less than an hour).
4) Keep tack of MoM, decisions, and action points in the confluence

**Comment by philipxujin** [comment]
@gregory1g , Thank you, I appreciate you taking the time to provide these suggestions. I believe they are practical ideas that align with our goals.

**Comment by chinaunicomyangfan** [comment]
@gregory1g Thanks for your suggestion,These information are very helpful for us.

**Comment by chinaunicomyangfan** [comment]
Have changed,Thank you for your suggestion.
