### ISSUE TITLE
Renaming from RegionUserCount into RegionDeviceCount - Tasks

### ISSUE THREAD

**Issue by hdamker** [camaraproject/RegionDeviceCount#26]
**Problem description**

As requested within https://github.com/camaraproject/APIBacklog/issues/48 and within the official request https://lists.camaraproject.org/g/tsc/topic/106929579 the Sub Project and its API repository has been renamed from RegionUserCount to RegionDeviceCount.

**Expected action**

Several tasks have to be executed (beyond the content of the repository):

- [x] Renaming of the repository (done by @hdamker)
- [x] PR with changes to README.md (see #25)
- [x] Change name within "About" of the repository
- [x] Name change of *_maintainers and *_codeowners GitHub teams
- [x] Change of Wiki pages
- [x] Change of Template pages within wiki (@wrathwolf)
- [x] Change of mailing list? (maybe not)
- [x] Change within website (@wrathwolf)
- [x] Change within CAMARA presentation (@MarkusKuemmerle)

**Additional context**

**Comment by hdamker** [comment]
@camaraproject/region-device-count_maintainers

**Comment by MarkusKuemmerle** [comment]
Will change the name in next version of CAMARA presentation

**Comment by chinaunicomyangfan** [comment]
Close as complete
