### ISSUE TITLE
Consider to communicate "next meeting" within meeting minutes and add link to meeting minutes to the README.

### ISSUE THREAD

**Issue by hdamker** [camaraproject/RegionDeviceCount#32]
**Problem description**

The information about the next meeting in README.md is outdated:
> The next meeting will be on Friday, Aug 2nd.

Proposal could be to point to the previous meeting minutes instead changing the README.md each time, see [here](https://github.com/camaraproject/QualityOnDemand/blob/main/README.md) for an example:

> For date/time of the next meeting, see previous meeting minutes

In addition a link to the meeting minutes is missing, see the structure of the template: https://github.com/camaraproject/Template_API_Repository/blob/main/README.md

**Expected action**

- Link to meeting minutes is added to the README.md, aligned with https://github.com/camaraproject/Template_API_Repository/blob/main/README.md
- Meeting minutes are available and are mention the date of the next meeting.

**Additional context**

Meeting minutes can be easily created with one click on the link on https://wiki.camaraproject.org/display/CAM/RegionDeviceCount.
Please consider also to migrate your meetings to the LFX Zoom platform.

**Comment by chinaunicomyangfan** [comment]
@hdamker  Thank you for the reminder.
May I ask how to establish an LFX Zoom meeting?

**Comment by hdamker** [comment]
> May I ask how to establish an LFX Zoom meeting?

Casey (@wrathwolf) or Evan (@eharrison24) can create the recurring meeting on the LFX Zoom platform for you.

**Comment by chinaunicomyangfan** [comment]
@wrathwolf Thanks for creating the LFX Zoom meeting,and the [PR](https://github.com/camaraproject/RegionDeviceCount/pull/34) has been merged.
@hdamker Thanks for your help.
I have informed all members of the information about the meeting changes.
